### PR TITLE
Latest version of express bus ticketing system

### PR DESCRIPTION
**Pull request by VoonChiCheng**
This is the latest of our pivotal tracker and we are doing for the bus schedule. We are doing 4 user story which is the Bus Schedule Homepage, Add bus schedule information, Update bus information and bus homepage. Choose which part of the user story you want to involve it. Noted that it should be average work to be done by all members. For the add bus schedule information with have 3 points of difficulty, more people are required to do it.

### CODE REVIEW

**Comment by teohzk** [comment]
Noted Scrum Master,I am going handle update bus information and bus homepage modules, will done as soon as possible.

**Comment by yikent** [comment]
Ok teohzk, but dont start your task first, because we havent discuss who will be taking those modules yet.

**Comment by VoonChiCheng** [comment]
Yi kent, you haven't stated which task you want to handle

**Comment by KaitoXion** [comment]
I'll post the modules in a while once i am infront of the pc. I'll be posting in both place, here and the pull request i've created. (KaitoXion-patch-1).

**Comment by VoonChiCheng** [comment]
no need.. just focus on 1 comment room.. just comment in here

**Comment by teohyunsheng** [comment]
I will handle add bus schedule information module.

**Comment by KaitoXion** [comment]
Hi,

I would like to contribute to the parts as follow:

1. Bus Schedule HomePage
2. Add Bus Schedule
3. Add new Bus Information
4. View Staff Details

Await for your reply, scrum master.

**Comment by VoonChiCheng** [comment]
Oh jasper, i don't think you can handle so much because we are doing for the 4 task as you written above, you don't mind that i assign you to any of the tasks?

**Comment by KaitoXion** [comment]
No, I'll await for your assignment :) 
Kindly suggest the best order best to go through.

**Pull request merged**
