### PR TITLE
Update bus_express_ticketing_system(latest).csv

### PR DESCRIPTION
**Pull request by VoonChiCheng**
I had uploaded the new user story that we are going to do in this iteration. Let's make discussion on which tasks you all are going to take on.

### CODE REVIEW

**Comment by yikent** [comment]
I will take the Update Bus Information part and  Seat Selection Page.

**Comment by teohyunsheng** [comment]
i am volunteer to handle the ticket exchange module together with one of the team member and one report.

**Comment by teohzk** [comment]
I think I will choose Ticket Order Homepage and View Staff Details.

**Comment by teohyunsheng** [comment]
i will choose the both search function in ticket ordering module and seat selection page,

**Comment by KaitoXion** [comment]
I'll choose:

1. Update Bus Information 
2. Ticket Order Search by Destination 

Need to choose another 2 more, right?

**Pull request merged**
