### PR TITLE
Update bus_express_ticketing_system(latest).csv

### PR DESCRIPTION
**Pull request by VoonChiCheng**
The latest tasks i had already uploaded. Choose which tasks you all want to choose. Please note that the tasks Payment Page need to be completed before proceed to other payment module. The tasks credit card payment page and cash payment page need to be done before proceed to print receipt,ticket and success payment page. Success Payment page is the last task that needed bo done

### CODE REVIEW

**Comment by KaitoXion** [comment]
Noted, will choose and post my update here later.

**Comment by yikent** [comment]
Okay noted.  I will choose.

**Comment by teohzk** [comment]
Will choose,later will inform you guys.

**Comment by teohzk** [comment]
I will handle Cash Payment Page and Print Receipt user stories.By the yun sheng which part of payment module you want to handle?

**Comment by KaitoXion** [comment]
User Story:
Process Multiple Order
Payment Page
Print Ticket

If this selection of mine post any problem, please let me know :)

**Comment by VoonChiCheng** [comment]
I had assigned all the tasks, can start working on it

**Comment by KaitoXion** [comment]
Right, proceeding.

**Comment by VoonChiCheng** [comment]
I had updated the member to work on the tasks, Zhang Kuan will helping to complete the credit card payment page and yun sheng will help to complete he cash payment page becasue both of them cannot proceed to their tasks before completing the cash and credit card payment page

**Comment by KaitoXion** [comment]
noted.

**Comment by teohzk** [comment]
got it,just finished the first task.

**Comment by VoonChiCheng** [comment]
Yi kent, can u replace yun sheng to do the print ticket task?

**Comment by teohyunsheng** [comment]
i will start to do the cash payment page now

**Comment by yikent** [comment]
I have started doing the print ticket function.

**Comment by teohzk** [comment]
Just started print receipt function.

**Comment by teohzk** [comment]
Just finished print receipt user story.

**Comment by KaitoXion** [comment]
user story:
Cash Payment Page

^ Done. 
only 1 user story?

**Comment by yikent** [comment]
I have done the print ticket function.

**Comment by teohyunsheng** [comment]
i have done cash payment page.

**Comment by KaitoXion** [comment]
1 user story due to time restriction. I guess so.

**Pull request merged**
