### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by VoonChiCheng**
I had assigned the tasks for you all and you all can start doing. I had also uploaded the previous last 2 week weekly report that i had forget to upload and also last week weekly report

### CODE REVIEW

**Comment by KaitoXion** [comment]
Noted. will proceed with the task.

Started on user story:
Generate Top 5 Route Report

**Comment by teohzk** [comment]
Noted .Just start Generate Top 5 Route Report user story and going to complete the first task.

**Comment by KaitoXion** [comment]
Noted. will proceed with the task.

Started on user story:
Generate Top 5 Route Report

Current moment Task that is done for the user story:
- Design template using jasper report plugin
- Let user choose the data they want to display in the report

new done task
- Design a UI for user to select their desired date
- Retrieve data from database

**Comment by teohzk** [comment]
Generate Top 5 Route Report user story is done. Now start to do Generate daily sales report user story.

**Comment by KaitoXion** [comment]
Same, working on it

**Comment by teohzk** [comment]
Due to typing error, I just now rename the last task of the Generate daily sales report user story.

**Comment by VoonChiCheng** [comment]
Me and Yun Sheng are done working with the ticket exchange and now both of us are focusing on generate monthly staff sales report

**Comment by yikent** [comment]
I have designed a UI for user to select their desired date.

**Comment by teohyunsheng** [comment]
I have designed a ui for user to select their date.

**Comment by teohzk** [comment]
Me and Jasper Pong just finished Generate daily sales report user story.

**Comment by yikent** [comment]
I managed to retrieve data from the database to generate the monthly sales summary report.

**Comment by KaitoXion** [comment]
Current updates:

User Story (Done):
1. Generate Top 5 Route Report
2. Generate daily sales report

All task is done

**Pull request merged**
