### PR TITLE
Update bus_express_ticketing_system(latest).csv

### PR DESCRIPTION
**Pull request by VoonChiCheng**
I had assigned the tasks to you all. Because the Ticker Order search by destination and Ticket Order search by destination and departure is a tasks that can only be done after the ticket order homepage so that this 2 tasks i will assign the member that did ticket order homepage. Anyone does not like the tasks i assigned to?

### CODE REVIEW

**Comment by KaitoXion** [comment]
I'll proceed as suggested/ assigned. Thank you for assigning :)

I'll give an update when there is a need here.

**Comment by KaitoXion** [comment]
Also, for continuous code upload; continuous integration will appear to be for the best instead of manual upload; kindly suggest the approach we will be following.

As for unit testing, since is possible we will be using tools that will be doing unit testing for us as well before the change is added into Github; by the tool.
Is their any suggestion how we will proceed with this in regard to unit test?

If needed, shall we seek for consultation?

**Comment by VoonChiCheng** [comment]
Tutor had said that she need to find the solution for the continuous integration problem. She will tell us the solution once she found it.

**Comment by VoonChiCheng** [comment]
I hope you all start doing your tasks as soon as possble

**Comment by teohyunsheng** [comment]
me and yi kent has started the update bus information today.

**Comment by teohzk** [comment]
I already started and finished the user stories of Ticket Order Searched by Destination and Multiple Order Confirmation Page.

**Comment by VoonChiCheng** [comment]
I am now done with my "View Staff Details" task and i will going to start the "Seat Selection" tasks soon

**Comment by VoonChiCheng** [comment]
Guys, accept the new invitation of pivotal tracker from ur gmail
because the trail version of my previous account is over and the project become readable only and i created a new account

**Comment by VoonChiCheng** [comment]
Guys... when you all doing ur tasks, please follow to the order from top to bottom which is the priority of the tasks

**Comment by yikent** [comment]
Noted. I have started the task Update Bus Information of the bus management module.

**Comment by teohzk** [comment]
Noted. I have started the Ticket Order Homepage of the ticket ordering module.

**Comment by KaitoXion** [comment]
User story:
Ticket Order Homepage

Task :

- Retrieve bus schedule information from database and display bus schedule information in form of table with the condition of the bus schedule date must be today or after today.
- Enable staff to directly select the schedule that the customer want to order by clicking on the schedule table.

Is updated and done. further work is in progress

**Comment by yikent** [comment]
i have started the Retrieve bus information from the database after user press the retrieve button function.

**Comment by teohzk** [comment]
Ticket Order Homepage of the ticket ordering module has been done.Now I am going to start the Ticket Order Search by Destination user story.

**Comment by teohyunsheng** [comment]
update bus information function done.

**Comment by VoonChiCheng** [comment]
Yi kent and yun sheng, let's start our "Seat Selection Page" tasks

**Comment by KaitoXion** [comment]
User Story:
- Ticket Order Search by Destination and Departure Date

Task done: 
- Display a date picker and a search button on top of the bus schedule table.

Working on; next:
- Show the bus schedule which the destination and the departure date of all the details in the bus schedule table is the destination and departure date that the user choose after the “Search” button is pressed.

**Comment by teohzk** [comment]
Order Search by Destination user story has been done.

**Comment by VoonChiCheng** [comment]
I completed 1 of the tasks inside "Seat selection Page". Which is the "Display the details of the bus schedule chosen, including destination, price, bus plate number, departure date and time."

**Comment by teohyunsheng** [comment]
"Seat Selection Page" Task - Display a list of seat with color to differentiate the status of the bus such as grey for unavailable, blue for available and green for chosen. (Completed)

**Comment by yikent** [comment]
i have done the Create checkbox list for the user to choose seat function.

**Comment by KaitoXion** [comment]
User Story:
1. Ticket Order Homepage
2. Ticket Order Search by Destination and Departure Date

All the tasks is completed.

**Comment by teohzk** [comment]
Just start multiple order confirmation page user story,I will finish this user story as soon as possible.

**Comment by KaitoXion** [comment]
Will be awaiting for request, as user story parts is done.

**Comment by teohzk** [comment]
Multiple order confirmation page user story is done. Please check thank you.

**Pull request merged**
