### PR TITLE
Update bus_express_ticketing_system(latest).csv

### PR DESCRIPTION
**Pull request by VoonChiCheng**
I had assigned you all to the task. For Zhang Kuan, you will be in charge with the Bus Schedule Homepage and Update Bus Information. For Jasper, you will be in charge with the Bus Homepage and also Update Bus Information. For me, Yun Sheng and Yi Kent, three of us will just focus on the Add Bus Schedule Information since the task is the hardest among those tasks. Do you all have any comment on the tasks i assigned to you all?

### CODE REVIEW

**Comment by teohzk** [comment]
Currently I am fine with my tasks. If later got any problems I will inform you guys to assist me.

**Comment by yikent** [comment]
I am okay with your arrangement.

**Comment by KaitoXion** [comment]
I'll wait for your reassignment. 
Kindly suggest for any change you did like to make.

**Comment by VoonChiCheng** [comment]
Hmm? What you meant by wait for my reassignment? You don't like with the tasks i assigned to you?

**Comment by teohyunsheng** [comment]
I am ok with your arrangement too

**Comment by VoonChiCheng** [comment]
Ok, if seems like there's no problem for now, then i suggest that we should start doing the task as soon as possible. If there's any problem while working on the tasks, then we will just discuss.

**Comment by KaitoXion** [comment]
I am fine and happy with your assignment. Kindly suggest the best task weight, to complete the task & meeting the requirement.

Thank you.

**Comment by KaitoXion** [comment]
I have seen the assignment in the pivoltal tracker. Will begin as suggested.

**Pull request merged**
